const employees = [{"emp_id":1001,"emp_fname":"Dene","emp_lname":"Shury","email":"dshury0@wordpress.com","experience":2,"profile_picture":''},
{"emp_id":1002,"emp_fname":"Ulrike","emp_lname":"Beteriss","email":"ubeteriss1@icq.com","experience":3,"profile_picture":''},
{"emp_id":1003,"emp_fname":"Alford","emp_lname":"Boynton","email":"aboynton2@domainmarket.com","experience":20,"profile_picture":''},
{"emp_id":1004,"emp_fname":"Clair","emp_lname":"Haquard","email":"chaquard3@bloomberg.com","experience":15,"profile_picture":''},
{"emp_id":1005,"emp_fname":"Zelig","emp_lname":"Lavall","email":"zlavall4@google.com.br","experience":7,"profile_picture":''},
{"emp_id":1006,"emp_fname":"Kellsie","emp_lname":"Maypother","email":"kmaypother5@cocolog-nifty.com","experience":7,"profile_picture":''},
{"emp_id":1007,"emp_fname":"Jarred","emp_lname":"Rhodes","email":"jrhodes6@businessinsider.com","experience":11,"profile_picture":''},
{"emp_id":1008,"emp_fname":"Mariska","emp_lname":"Hackleton","email":"mhackleton7@fotki.com","experience":17,"profile_picture":''},
{"emp_id":1009,"emp_fname":"Petr","emp_lname":"Tuffley","email":"ptuffley8@marketwatch.com","experience":9,"profile_picture":''},
{"emp_id":1010,"emp_fname":"Nico","emp_lname":"Ygoe","email":"nygoe9@pinterest.com","experience":4,"profile_picture":''}];

const employeeSkills = [{"id":1,"emp_id":1001,"skill_category":"frontend","skill_name":"React","experience":4,"num_proj_impl":108},
{"id":2,"emp_id":1001,"skill_category":"backend","skill_name":"Hadoop","experience":28,"num_proj_impl":149},
{"id":3,"emp_id":1001,"skill_category":"integration","skill_name":"Java","experience":4,"num_proj_impl":4},
{"id":4,"emp_id":1001,"skill_category":"data engineering","skill_name":"Golang","experience":43,"num_proj_impl":124},
{"id":5,"emp_id":1003,"skill_category":"frontend","skill_name":"Java","experience":9,"num_proj_impl":182},
{"id":6,"emp_id":1003,"skill_category":"backend","skill_name":"Angular","experience":49,"num_proj_impl":46},
{"id":7,"emp_id":1003,"skill_category":"data analyst","skill_name":"HTML","experience":23,"num_proj_impl":142},
{"id":8,"emp_id":1003,"skill_category":"frontend","skill_name":"React","experience":18,"num_proj_impl":24},
{"id":9,"emp_id":1005,"skill_category":"data engineering","skill_name":"CSS","experience":1,"num_proj_impl":162},
{"id":10,"emp_id":1005,"skill_category":"data analyst","skill_name":"Springboot","experience":13,"num_proj_impl":61},
{"id":11,"emp_id":1005,"skill_category":"frontend","skill_name":"css","experience":16,"num_proj_impl":57},
{"id":12,"emp_id":1005,"skill_category":"frontend","skill_name":"HTML","experience":18,"num_proj_impl":7},
{"id":13,"emp_id":1005,"skill_category":"frontend","skill_name":"HTML","experience":13,"num_proj_impl":60},
{"id":14,"emp_id":1005,"skill_category":"integration","skill_name":"HTML","experience":30,"num_proj_impl":4},
{"id":15,"emp_id":1008,"skill_category":"backend","skill_name":"Java","experience":10,"num_proj_impl":194},
{"id":16,"emp_id":1008,"skill_category":"data engineering","skill_name":"Golang","experience":22,"num_proj_impl":148},
{"id":17,"emp_id":1008,"skill_category":"data analyst","skill_name":"Angular","experience":50,"num_proj_impl":34},
{"id":18,"emp_id":1008,"skill_category":"frontend","skill_name":"Angular","experience":21,"num_proj_impl":173},
{"id":19,"emp_id":1008,"skill_category":"frontend","skill_name":"MongoDB","experience":30,"num_proj_impl":150},
{"id":20,"emp_id":1008,"skill_category":"backend","skill_name":"css","experience":12,"num_proj_impl":174},
{"id":21,"emp_id":1008,"skill_category":"data engineering","skill_name":"HTML","experience":45,"num_proj_impl":122},
{"id":22,"emp_id":1007,"skill_category":"integration","skill_name":"CSS","experience":8,"num_proj_impl":85},
{"id":23,"emp_id":1007,"skill_category":"integration","skill_name":"Angular","experience":34,"num_proj_impl":57},
{"id":24,"emp_id":1007,"skill_category":"frontend","skill_name":"SQL","experience":33,"num_proj_impl":88},
{"id":25,"emp_id":1010,"skill_category":"data engineering","skill_name":"HTML","experience":28,"num_proj_impl":88},
{"id":26,"emp_id":1010,"skill_category":"backend","skill_name":"MongoDB","experience":45,"num_proj_impl":75},
{"id":27,"emp_id":1010,"skill_category":"backend","skill_name":"MongoDB","experience":26,"num_proj_impl":93},
{"id":28,"emp_id":1002,"skill_category":"data engineering","skill_name":"Springboot","experience":48,"num_proj_impl":164},
{"id":29,"emp_id":1002,"skill_category":"frontend","skill_name":"Angular","experience":45,"num_proj_impl":128},
{"id":30,"emp_id":1002,"skill_category":"integration","skill_name":"css","experience":5,"num_proj_impl":14},
{"id":31,"emp_id":1002,"skill_category":"integration","skill_name":"React","experience":33,"num_proj_impl":36},
{"id":32,"emp_id":1002,"skill_category":"data analyst","skill_name":"CSS","experience":31,"num_proj_impl":164},
{"id":33,"emp_id":1004,"skill_category":"frontend","skill_name":"Hadoop","experience":37,"num_proj_impl":86},
{"id":34,"emp_id":1004,"skill_category":"backend","skill_name":"Java","experience":8,"num_proj_impl":79},
{"id":35,"emp_id":1004,"skill_category":"frontend","skill_name":"SQL","experience":29,"num_proj_impl":187},
{"id":36,"emp_id":1004,"skill_category":"integration","skill_name":"css","experience":20,"num_proj_impl":122},
{"id":37,"emp_id":1009,"skill_category":"data engineering","skill_name":"React","experience":13,"num_proj_impl":53},
{"id":38,"emp_id":1009,"skill_category":"data engineering","skill_name":"Springboot","experience":30,"num_proj_impl":89},
{"id":39,"emp_id":1009,"skill_category":"frontend","skill_name":"SQL","experience":46,"num_proj_impl":73},
{"id":40,"emp_id":1009,"skill_category":"integration","skill_name":"SQL","experience":36,"num_proj_impl":153}];

const skills = [{"skill_id":1,"skill_category":"backend","skill_name":"Java"},
{"skill_id":2,"skill_category":"frontend","skill_name":"Java"},
{"skill_id":3,"skill_category":"data engineering","skill_name":"SQL"},
{"skill_id":4,"skill_category":"integration","skill_name":"Angular"},
{"skill_id":5,"skill_category":"backend","skill_name":"Springboot"},
{"skill_id":6,"skill_category":"data analyst","skill_name":"JS"},
{"skill_id":7,"skill_category":"backend","skill_name":"Hadoop"},
{"skill_id":8,"skill_category":"backend","skill_name":"CSS"},
{"skill_id":9,"skill_category":"integration","skill_name":"SQL"},
{"skill_id":10,"skill_category":"backend","skill_name":"CSS"},
{"skill_id":11,"skill_category":"integration","skill_name":"CSS"},
{"skill_id":12,"skill_category":"backend","skill_name":"MongoDB"},
{"skill_id":13,"skill_category":"backend","skill_name":"css"},
{"skill_id":14,"skill_category":"integration","skill_name":"Springboot"},
{"skill_id":15,"skill_category":"backend","skill_name":"CSS"},
{"skill_id":16,"skill_category":"integration","skill_name":"Springboot"},
{"skill_id":17,"skill_category":"data analyst","skill_name":"JS"},
{"skill_id":18,"skill_category":"data analyst","skill_name":"CSS"},
{"skill_id":19,"skill_category":"data engineering","skill_name":"React"},
{"skill_id":20,"skill_category":"integration","skill_name":"Springboot"},
{"skill_id":21,"skill_category":"backend","skill_name":"Golang"},
{"skill_id":22,"skill_category":"frontend","skill_name":"Hadoop"},
{"skill_id":23,"skill_category":"data analyst","skill_name":"CSS"},
{"skill_id":24,"skill_category":"frontend","skill_name":"CSS"},
{"skill_id":25,"skill_category":"backend","skill_name":"css"},
{"skill_id":26,"skill_category":"data analyst","skill_name":"SQL"},
{"skill_id":27,"skill_category":"backend","skill_name":"css"},
{"skill_id":28,"skill_category":"integration","skill_name":"JS"},
{"skill_id":29,"skill_category":"data analyst","skill_name":"HTML"},
{"skill_id":30,"skill_category":"integration","skill_name":"Angular"},
{"skill_id":31,"skill_category":"integration","skill_name":"React"},
{"skill_id":32,"skill_category":"data engineering","skill_name":"Angular"},
{"skill_id":33,"skill_category":"integration","skill_name":"Hadoop"},
{"skill_id":34,"skill_category":"backend","skill_name":"Springboot"},
{"skill_id":35,"skill_category":"data analyst","skill_name":"Hadoop"},
{"skill_id":36,"skill_category":"data analyst","skill_name":"SQL"},
{"skill_id":37,"skill_category":"integration","skill_name":"JS"},
{"skill_id":38,"skill_category":"backend","skill_name":"css"},
{"skill_id":39,"skill_category":"frontend","skill_name":"css"},
{"skill_id":40,"skill_category":"integration","skill_name":"Angular"},
{"skill_id":41,"skill_category":"data analyst","skill_name":"MongoDB"},
{"skill_id":42,"skill_category":"integration","skill_name":"css"},
{"skill_id":43,"skill_category":"frontend","skill_name":"Springboot"},
{"skill_id":44,"skill_category":"data analyst","skill_name":"MongoDB"},
{"skill_id":45,"skill_category":"backend","skill_name":"CSS"},
{"skill_id":46,"skill_category":"backend","skill_name":"Golang"},
{"skill_id":47,"skill_category":"data engineering","skill_name":"JS"},
{"skill_id":48,"skill_category":"data engineering","skill_name":"Hadoop"},
{"skill_id":49,"skill_category":"integration","skill_name":"Java"},
{"skill_id":50,"skill_category":"data analyst","skill_name":"HTML"}];

module.exports = {
  employees,
  employeeSkills,
  skills
}