version: '3'
services:
  app:
    build: .
    ports:
    - "3000:3000"
    volumes:
    - .:/usr/src/app
    depends_on:
      - "mySql"
  mySql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_DATABASE=skillcentral
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: