version: '3.1'
services:
  app:
    build: .
    ports:
    - "3000:3000"
    volumes:
    - .:/usr/src/app
    depends_on:
      - "mySql"
  mySql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: topsecret
      MYSQL_DATABASE: skillcentral
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - mysql-volume-skillcentral:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
volumes:
  mysql-volume-skillcentral: